version: '3.8'
services:
    agent1:
      image: jenkins/ssh-agent:alpine-jdk17
      privileged: true
      user: root
      environment:
        JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCECYfh2DPFxu6lJ/VvwIUSvtbw0Q6bOxEGKl80CBGhfqscGW/73IoSJPNKaM4/+KEqLnlYE5PuDxm5qKCBKMlmzLthC6mu6H3zSNMcLO/BbaqwCE2EbNZyBlex3bvsIV4Ng/TAZTnaGnFB3+S/32VqTcttiO0pEO9ZaO9XR6IIEIBo0y6oZGhCvplmDfeqgjM09yMnRNpAhppeChOw6nEBhNIWozoZ8v4jG4TEMqh3kKpaN+WHgQRkmqNro4T4idMNqDVsSerDp4yOZPPh3k+VKV+AQfdenTysYbDXFJZ96MNOo2TKmubtvJFxlb69ZIv+6F3coYEnQUD39DZJK66WgynwEJxw9RHrRzG2a2TyT0UfPi4uBLhTujrMXdLKTFa8q5lznd4owa2CiO4vzKVRVbIGFr8JT3zpP9fvIb3eSmO+1sBHSjkYwRBqzYl6T8WD0KOv3zdsqDRAKwDR8aJYt1D2kVhQ59vlsTFgvNaZJIjpbJc0CYlKn/EqDFN4yQ8= root@ef44899fa698
      ports:
        - "4444:22"
      container_name: jenkins_agent1

    agent2:
      image: javacream/jenkins_ssh_agent:1.0
      privileged: true
      user: root
      environment:
        JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCECYfh2DPFxu6lJ/VvwIUSvtbw0Q6bOxEGKl80CBGhfqscGW/73IoSJPNKaM4/+KEqLnlYE5PuDxm5qKCBKMlmzLthC6mu6H3zSNMcLO/BbaqwCE2EbNZyBlex3bvsIV4Ng/TAZTnaGnFB3+S/32VqTcttiO0pEO9ZaO9XR6IIEIBo0y6oZGhCvplmDfeqgjM09yMnRNpAhppeChOw6nEBhNIWozoZ8v4jG4TEMqh3kKpaN+WHgQRkmqNro4T4idMNqDVsSerDp4yOZPPh3k+VKV+AQfdenTysYbDXFJZ96MNOo2TKmubtvJFxlb69ZIv+6F3coYEnQUD39DZJK66WgynwEJxw9RHrRzG2a2TyT0UfPi4uBLhTujrMXdLKTFa8q5lznd4owa2CiO4vzKVRVbIGFr8JT3zpP9fvIb3eSmO+1sBHSjkYwRBqzYl6T8WD0KOv3zdsqDRAKwDR8aJYt1D2kVhQ59vlsTFgvNaZJIjpbJc0CYlKn/EqDFN4yQ8= root@ef44899fa698
      ports:
        - "4445:22"
      container_name: jenkins_agent2
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

